### ISSUE TITLE
`ob storage create-policy` breaks parsing the `--benchmark` arg

### ISSUE THREAD

**Issue by imallona** [omnibenchmark/omnibenchmark#236]
`ob storage create-policy -b  Clustering_conda.yml` breaks with `TypeError: create_policy() got an unexpected keyword argument 'benchmark'` after the refactor, but works in `0.3.2`.

Using the `0.3.0.post47` (after the refactor, https://github.com/omnibenchmark/omnibenchmark/pull/227 if I'm not wrong). Originally reported by Mark, and reproduced below.

<details>

```bash
(omnibenchmark) [user@laptop clustering_example]$ ob storage create-policy -b  Clustering_conda.yml
Traceback (most recent call last):
  File "/home/imallona/miniconda3/envs/omnibenchmark/bin/ob", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/imallona/miniconda3/envs/omnibenchmark/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imallona/miniconda3/envs/omnibenchmark/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/imallona/miniconda3/envs/omnibenchmark/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imallona/miniconda3/envs/omnibenchmark/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imallona/miniconda3/envs/omnibenchmark/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imallona/miniconda3/envs/omnibenchmark/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_policy() got an unexpected keyword argument 'benchmark'
(omnibenchmark) [user@laptop clustering_example]$ ob storage create-policy  Clustering_conda.yml
Usage: ob storage create-policy [OPTIONS]
Try 'ob storage create-policy --help' for help.

Error: Missing option '-b' / '--benchmark'.
(omnibenchmark) [user@laptop clustering_example]$ ob --version
OmniBenchmark CLI, version 0.3.0.post47
```
</details>

Works on 0.3.2

<details>

```bash
(omnibenchmark) [user@laptop clustering_example]$ ob storage create-policy -b  Clustering_conda.yml
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::clusteringexampleconda/*",
        "arn:aws:s3:::clusteringexampleconda"
      ]
    },
    {
      "Effect": "Deny",
      "Action": [
        "s3:BypassGovernanceRetention",
        "s3:DeleteObjectTagging",
        "s3:DeleteObjectVersion",
        "s3:DeleteObjectVersionTagging",
        "s3:DeleteBucket",
        "s3:DeleteBucketPolicy"
      ],
      "Resource": [
        "arn:aws:s3:::clusteringexampleconda/*",
        "arn:aws:s3:::clusteringexampleconda"
      ]
    }
  ]
}
(omnibenchmark) [user@laptop clustering_example]$ ob --version
OmniBenchmark CLI, version 0.3.2

```
</details>

**Comment by btraven00** [comment]
#237 merged into dev
